name: Use Timestamp Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Time Stamp Action
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Use Time Stamp Action
        uses: ./
        id: timestamp
        with:
          timezone: 'America/New_York'
