name: Use Timestamp Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Time Stamp Action
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Use Time Stamp Action
        uses: notsogaurab/current-timestamp-action@v1.0
        id: timestamp
        with:
          timezone: 'America/New_York'
