name: Use Timestamp Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Time Stamp Action
    steps:
      - uses: actions/checkout@v3

      - name: Use Time Stamp Action
        uses: ./
        id: timestamp
        with:
          timezone: 'America/New_York'
